### ISSUE TITLE
Вынести путь до конфигурационного файла в переменные окружения

### ISSUE THREAD

**Issue by sermer07** [s-nataliy/chatops-awx#1]
В нашей реализации конфигурационный файл будет прокидываться с помощью vault injector по пути /vault/secrets. Имя файла также может измениться. Прошу включить возможность указания пути до конфигурационного файла с помощью переменной окружения.

**Comment by s-nataliy** [comment]
Реализовано использование переменной окружения "CONFIG_FILE_PATH"
